language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: X4erFhyHIl2cQM+ex2/dcB3HolwW2NXe6mHXMd2g83WT6tQQTjhrUFlL2pSWgv4DSPwoldDSL5Wl43LxImJ0GFGTTyGl8CtiuiFh9512x5RTmtiZems8xaXeiSPnJbxZmK9aX7rO+xJVjOn9xOoWjA9PZyjNyGtvpiPecOS6B7ySHTVsEFz6qb7BmIPqpKxZLOQrCXYfhH3pEPG4MBCaItZgCEk01HsYokVtV/tigEo9fRiaMn947uQEs2veVWh5WUSqjBdtC3TnUm+PALFHAJevXM3S+P9nP+Ql+fzNJKMFa7tl8/dvG2OXr+7X7fsLHcwSCDYsJGLXYeAkmeHPey+CQdOsZx1Kb9OWKBEcxdFRy1rshpAxNCc7/JNUkO6A7GMJD2VFek7lTs724/9EDA08Oi5/s3KZ6WKYlVnIJIC4mjzFtTMYxPFZe9Yvcycye2usIGk0c/9S5MEcAIs3FeE5RnNjF7cSNdQGNqVDHBNrwACPpXZ9dKbr7AIYbszDcM7VDEvKiDyRJP3cVyiutt+nMyEl949oX97V8h3pV1AaYp/GgjtXphfwpT5KLELSN0zzILgyySVr43FDkD3YVBNBB21VelkpBUNBTz00S8AyYJM4xenFemU0JOgpIGGp4nmFmwg3gUzsBZOGXjqqb0Gm1VOVNrEaQG5LBi6Fj1o=
  app: mikeflynncodes
  skip_cleanup: true